#!/bin/bash          

./mkbootimg --base 0x00000000 --kernel zImage --ramdisk_offset 0x02008000 --tags_offset 0x01E00000 --pagesize 2048 --cmdline "console=ttyHSL0,115200,n8 androidboot.hardware=qcom user_debug=31 ehci-hcd.park=3 zcache androidboot.selinux=permissive" --ramdisk boot.img-ramdisk.gz --dt dt.img -o boot.img
